version: '3.8'

services:
  app:
    image: 'docker-spring-boot-postgres:latest'
    build:
      context: .
      dockerfile: Dockerfile
      args:
        JAR_FILE: target/booking-system-1.0-SNAPSHOT.jar
    ports:
      - "8080:8080"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/bookingdb
      - SPRING_DATASOURCE_USERNAME=bookinguser
      - SPRING_DATASOURCE_PASSWORD=bookingpass
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update
    depends_on:
      - db

  db:
    image: postgres:latest
    environment:
      - POSTGRES_DB=bookingdb
      - POSTGRES_USER=bookinguser
      - POSTGRES_PASSWORD=bookingpass
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: